// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ajrswsxnlkgauhkiedfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqcnN3c3hubGtnYXVoa2llZGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTg4NjUsImV4cCI6MjA2NzQ3NDg2NX0.0gUHAsEOEVxZwjOizqQ6bbcSIBxsEGwDNIDJ5xWVXpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});